name: Get recent youtube videos

on:
    schedule:
        - cron: "0 15 * * *"
    push:
        paths:
            - ".github/scripts"
    workflow_dispatch:

jobs:
    fetch-youtube:
        name: Get recent youtube videos
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: "16"
                  check-latest: true
                  registry-url: https://registry.npmjs.org/
            - name: Run script
              run: |
                  chmod +x ./.github/scripts/fetch-youtube.sh
                  ./.github/scripts/fetch-youtube.sh
            - name: Commit
              run: |
                  chmod +x ./.github/scripts/commit.sh
                  ./.github/scripts/commit.sh
              env:
                  TOKEN: ${{ secrets.TOKEN }}
                  REPOSITORY: ${{ github.repository }}
                  MESSAGE: "Update YouTube video list"
